version: '3.4'
services:
  rocketpool.avado.dnp.dappnode.eth:
    image: 'rocketpool.avado.dnp.dappnode.eth:0.0.79'
    build:
      context: ./build
      args:
        RP_VERSION: v1.6.0
    volumes:
      - 'rocketpool:/rocketpool'
    environment:
      - NETWORK=mainnet
      - CONSENSUSCLIENT=prysm
      - EXTRA_OPTS=
volumes:
  rocketpool: {}
