version: '3.4'
services:
  rocketpool.avado.dnp.dappnode.eth:
    image: 'rocketpool.avado.dnp.dappnode.eth:0.0.60'
    build:
      context: ./build
      args:
        PRYSM_VERSION: v2.0.6
        RP_VERSION: v1.2.4
    volumes:
      - 'rocketpool:/rocketpool'
    environment:
      - NETWORK=mainnet
      - EXTRA_OPTS=
volumes:
  rocketpool: {}
