version: '3.4'
services:
  rocketpool.avado.dnp.dappnode.eth:
    image: 'rocketpool.avado.dnp.dappnode.eth:0.0.2'
    build:
      context: ./build
      args:
        RP_VERSION: v1.1.2
        PRYSM_VERSION: v2.0.5
    volumes:
      - 'rocketpool:/rocketpool'
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - EXTRA_OPTS=
volumes:
  rocketpool: {}
